---
services:
  doctors-app:
    container_name: doctors-app
    restart: always
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--reload"]
    volumes:
      - ../src:/home/alex-user/src
    ports:
      - 8088:8000
    depends_on:
      - postgres-db
      - postgres-db-test

  postgres-db:
    image: postgres:17
    container_name: postgres-db
    ports:
      - "5490:5432"
    environment:
      POSTGRES_USER: doctors
      POSTGRES_PASSWORD: doctors
      POSTGRES_DB: doctors
    volumes:
      - doctors:/var/lib/postgresql/data

  postgres-db-test:
    image: postgres:17
    container_name: postgres-db-test
    ports:
      - "5491:5432"
    environment:
      POSTGRES_USER: doctors
      POSTGRES_PASSWORD: doctors
      POSTGRES_DB: doctors

volumes:
  doctors:
